version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  
jobs:
  notification:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - slack/notify:
          channel: ${slack_channel_id}
          color: '#42e2f4'
          message: ${test_message}
          webhook: ${slack_webhook}
          
          
workflows:
  version: 2
  build_and_test:
    jobs:
     - notification:
          context: 
            # 以下のContextのうち、Slack および test_duplicate_key の両者にも slack_webhook というkeyを登録している。
            # 同じ文字列の key が異なる Context で重複している場合、併記されている順序があとの key の value を読んでいる
            # 仮に↓の順序を入れ替えてSlack、test_duplicate_key の順に併記すると、test_duplicate_key の誤った value を読むのでエラーに。
            - test_duplicate_key
            - Slack
            - test
            - docker-hub-creds


