version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  
jobs:
  notification:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          channel: ${slack_channel_id}
          color: '#42e2f4'
          message: "これはテストです。"
          webhook: ${slack_webhook}
          
          
workflows:
  version: 2
  build_and_test:
    jobs:
     - notification:
          context: Slack
